services:
  - type: web
    name: cantine-app
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CRON_SECRET
        generateValue: true
      - key: TEAMS_WEBHOOK_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: ADMIN_BOOTSTRAP_NAME
        sync: false
      - key: ADMIN_BOOTSTRAP_CODE
        sync: false
      - key: PROVIDER_BOOTSTRAP_NAME
        sync: false
      - key: PROVIDER_BOOTSTRAP_CODE
        sync: false
